### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by B4rabbas** [TheGag96/sm64-port#3]
Hi, the patch brake the compilation
Here is log file
![sm64pcBuilder2_xiUwxx9pQJ](https://user-images.githubusercontent.com/36156012/94339627-8fa43900-fffb-11ea-8221-6ed2ee6917f2.png)
[failed compilation.txt](https://github.com/TheGag96/sm64-port/files/5286580/failed.compilation.txt)

**Comment by TheGag96** [comment]
Looks like you're trying to base this off of Render96. Try [this](https://github.com/TheGag96/sm64ex/releases/tag/v1.01a) version of the patch I made for that.

Let me know if you get it working - I'll close out this issue when you do. Have fun!

**Comment by B4rabbas** [comment]
Unfortunatly it don't.

[failed compilation.txt](https://github.com/TheGag96/sm64-port/files/5287270/failed.compilation.txt)
![sm64pcBuilder2_1WyA4elSL3](https://user-images.githubusercontent.com/36156012/94349507-2a753580-0045-11eb-8f44-5172af0c2fbd.png)

**Comment by TheGag96** [comment]
I think the Cheater patch is conflicting... Are you able to edit files in the repo directly after patches are applied? If all else fails, in `include/text_options_strings.h.in`, try addding:

```c
#define TEXT_BIND_DPAD_RIGHT _("D-pad Right")
```

right under the line:

```c
#define TEXT_BIND_C_RIGHT    _("C-Right")
```

**Comment by B4rabbas** [comment]
Yes it was a conflict with cheat mod.
Work flawessly right now

**Comment by TheGag96** [comment]
Awesome, glad to hear! I wish there was a better solution to have multiple patches in the same build. It would really require a full modding API, but even then, it probably wouldn't allow for the deep edits we all enjoy doing lol.

**Comment by B4rabbas** [comment]
Yop, there is no big deal. Thanks for your mod (the gameplay is so much better). I close the ticket.
